CREATE TABLE `ShipmentDetails` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `user_id` INT(11) NULL DEFAULT NULL,
    `date` DATETIME NULL DEFAULT NULL,
    `planta` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `code_planta` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `transport` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `in_out_bound` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `cost_euros` DECIMAL(15,2) NULL DEFAULT NULL,
    `description` TEXT COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `area` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `int_ext` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `paid_by` VARCHAR(100) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `category_cause` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `project_status` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `recovery` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `weight` FLOAT NULL DEFAULT NULL,
    `measures` VARCHAR(100) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `products` VARCHAR(100) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `carrier` VARCHAR(100) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `quoted_cost` DECIMAL(15,2) NULL DEFAULT NULL,
    `reference` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `reference_number` VARCHAR(50) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    `origin_id` INT(11) NULL DEFAULT NULL,
    `destiny_id` INT(11) NULL DEFAULT NULL,
    `status_id` INT(11) NULL DEFAULT 1,
    `required_auth_level` INT(11) NULL DEFAULT 1,
    `moneda` VARCHAR(3) COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_origin_id` (`origin_id`),
    INDEX `idx_destiny_id` (`destiny_id`),
    INDEX `idx_status_id` (`status_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;